/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CMS;

/**
 *
 * @author Lenovo
 */
public class DeliveryStaff extends javax.swing.JFrame {

    /**
     * Creates new form DeliveryStaff
     */
    public DeliveryStaff() {
        initComponents();
    }
    
    public DeliveryStaff(String i) {
        this.jTextFieldID.setText(i);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jButtonMyProfile = new javax.swing.JButton();
        jTextFieldID = new javax.swing.JTextField();
        jButtonViewOrder = new javax.swing.JButton();
        jButtonFeedback = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        jLabelTitle.setFont(new java.awt.Font("Poppins", 1, 30)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(153, 204, 255));
        jLabelTitle.setText("Delivery Staff Menu");

        jButtonMyProfile.setBackground(new java.awt.Color(183, 241, 255));
        jButtonMyProfile.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jButtonMyProfile.setForeground(new java.awt.Color(43, 22, 130));
        jButtonMyProfile.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Pictures\\FIgma Designs\\edit.png")); // NOI18N
        jButtonMyProfile.setText("My Profile");
        jButtonMyProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMyProfileActionPerformed(evt);
            }
        });

        jTextFieldID.setEditable(false);
        jTextFieldID.setBackground(new java.awt.Color(0, 51, 102));
        jTextFieldID.setBorder(null);
        jTextFieldID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIDActionPerformed(evt);
            }
        });

        jButtonViewOrder.setBackground(new java.awt.Color(183, 241, 255));
        jButtonViewOrder.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jButtonViewOrder.setForeground(new java.awt.Color(43, 22, 130));
        jButtonViewOrder.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Pictures\\FIgma Designs\\editOrder.png")); // NOI18N
        jButtonViewOrder.setText("View/Update Orders");
        jButtonViewOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewOrderActionPerformed(evt);
            }
        });

        jButtonFeedback.setBackground(new java.awt.Color(183, 241, 255));
        jButtonFeedback.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jButtonFeedback.setForeground(new java.awt.Color(43, 22, 130));
        jButtonFeedback.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Pictures\\FIgma Designs\\feedback.png")); // NOI18N
        jButtonFeedback.setText("Feedback");
        jButtonFeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFeedbackActionPerformed(evt);
            }
        });

        jButtonBack.setBackground(new java.awt.Color(51, 204, 255));
        jButtonBack.setFont(new java.awt.Font("Poppins Medium", 0, 13)); // NOI18N
        jButtonBack.setForeground(new java.awt.Color(0, 51, 102));
        jButtonBack.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Pictures\\FIgma Designs\\backBtn.png")); // NOI18N
        jButtonBack.setText("Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(jButtonFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonBack)
                                .addGap(132, 132, 132)
                                .addComponent(jLabelTitle))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonMyProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(jButtonViewOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTitle)
                    .addComponent(jButtonBack))
                .addGap(74, 74, 74)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonMyProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonViewOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jButtonFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMyProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMyProfileActionPerformed
        // TODO add your handling code here:
        MyProfile profile = new MyProfile();
        String id = jTextFieldID.getText();
        profile.jTextID.setText(id);
        profile.loadProfile();
        profile.setVisible(true);
    }//GEN-LAST:event_jButtonMyProfileActionPerformed

    private void jTextFieldIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDActionPerformed

    private void jButtonViewOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewOrderActionPerformed
        // TODO add your handling code here:
        ViewAssignedOrder ao = new ViewAssignedOrder();
        String aoid = jTextFieldID.getText();
        ao.jTextFieldDelvID.setText(aoid);
        ao.addRow();
        ao.setVisible(true);
        
    }//GEN-LAST:event_jButtonViewOrderActionPerformed

    private void jButtonFeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFeedbackActionPerformed
        // TODO add your handling code here:
        AddFeedback af = new AddFeedback();
        String afID = jTextFieldID.getText();
        af.jTextFieldDelvID.setText(afID);
        af.addRow();
        af.setVisible(true);
        
    }//GEN-LAST:event_jButtonFeedbackActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        // TODO add your handling code here:
        LoginFrame login = new LoginFrame();
        this.dispose();
        login.setVisible(true);
    }//GEN-LAST:event_jButtonBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeliveryStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeliveryStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeliveryStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeliveryStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeliveryStaff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonFeedback;
    private javax.swing.JButton jButtonMyProfile;
    private javax.swing.JButton jButtonViewOrder;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JTextField jTextFieldID;
    // End of variables declaration//GEN-END:variables
}
